---
title: "R Notebook"
output: html_notebook
---


```{r}
library(ggplot2)
library(ggfx)
```


```{r}
greeting_card <- function(width, 
                          height, 
                          text, 
                          text_width, 
                          text_x,
                          text_y,
                          family,
                          background_colour, 
                          text_colour) {
  
  plot <- ggplot() +
    geom_rect(
      aes(
        xmin = 1, 
        xmax = width, 
        ymin = 1, 
        ymax = height
        ),
      fill = background_colour
      ) +
    annotate("text", 
             x = text_x, 
             y = text_y, 
             size = 10, 
             color = text_colour, family = family, 
             label = stringr::str_wrap(
               text, 
               width = text_width
               )
             ) +
    theme_void()
  
  return(plot)
  
  
  
}

greeting_card(width = 5, 
              height = 7, 
              text = "Hello World", 
              text_width = 10, 
              text_x = 3,
              text_y = 4,
              family = "serif",
              background_colour = "orange", 
              text_colour = "white")
 
```

```{r}
 ggplot() +
  with_shadow(geom_rect(
      aes(
        xmin = 1, 
        xmax = 5, 
        ymin = 1, 
        ymax = 7
        ),
      fill = "orange"), sigma = 1, colour = "darkgrey") +
  theme_void()
```


```{r}
ggplot() + 
  geom_rect(aes(xmin = 1, xmax = 3, ymin = 10, ymax = 15),
            fill = "orange") +
  annotate("text", x = 2, y = 12.5, size = 8, color = "white", family = font,
           label = stringr::str_wrap(
             "wheras the inhereant dignity of human life and other things to type", 
             width = 20
             )
  ) +
  theme_void()
```

